
services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://myuser:password@db:5432/hr_database"
    volumes:
      - ./app:/migration/app
      - ./tests:/migration/tests

volumes:
   postgres_data: